### ISSUE TITLE
Improvement: when opening categoriepage automatically scroll to the top of the page

### ISSUE THREAD

**Issue by rgrnetalk** [SanderKlootwijk/harbour-nednieuws#1]
Hi Sander, good app, I use it to read the news, so I no longer have to open nu.nl in the browser (the content of nu.nl was becoming worse anyway)... thanks for the app!

**Small improvement:** 
when opening categoriepage automatically scroll to the top of the page

**Steps to reproduce:** 
Open a categorie page 
Scroll down to the lower part of the page
Go back to the categories page 
Open another categorie page

**Expected result:** 
The selected categorie page opens with the top part with the latest news

**Actual result:**
The selected categorie page opens with the lower part of the page, so you have to scroll to the top of the page to read the newest news items

**Comment by SanderKlootwijk** [comment]
Great to hear that the app is useful for you! I'll try to fix this bug as soon as possible.

**Comment by SanderKlootwijk** [comment]
Fixed in version 1.1.1! This release will show up soon in the Jolla store ;)

**Comment by rgrnetalk** [comment]
Well done! Thank you very much for the swift fix!
