### ISSUE TITLE
Empty main screen screen in SFOS 4

### ISSUE THREAD

**Issue by a-dekker** [SanderKlootwijk/harbour-nednieuws#2]
Hello Sander,
It seems your app does not work in the early release of SFOS 4, the main screen remains empty.
Removing the "visible: false" line after "id: mainPage" in FirstPage.qml fixed it for me

**Comment by SanderKlootwijk** [comment]
Hi @a-dekker! Thank you for addressing this issue. I currently don't use Sailfish anymore (I'm using a Volla with Ubuntu Touch now), but I've still got my XA2 so I should be able to flash SFOS on it again. At the moment SFOS 4 is only available for early access, right? Am I able to install it with a developer account? If so, I'll flash SFOS 4 on my XA2, fix it and push an update to the Jolla Store.

**Comment by a-dekker** [comment]
I could create a PR for you, I can test it on both SFOS 4 and SFOS 3 (my old Jolla 1 phone does not receive updates beyond the latest SFOS 3). It could spare you the time of reflashing.

**Comment by SanderKlootwijk** [comment]
That would be great. Thank you in advance!

**Comment by a-dekker** [comment]
Should be fixed by https://github.com/SanderKlootwijk/harbour-nednieuws/pull/3

**Comment by SanderKlootwijk** [comment]
Great, thank you! I'll push the update somewhere next week to the Jolla Store.
