### ISSUE TITLE
feeds.nos.nl ipv feeds.feedburner.com

### ISSUE THREAD

**Issue by Fuzzillogic** [SanderKlootwijk/harbour-nednieuws#9]
De feeds via feedburner lijken vaak achter te lopen t.o.v. die van de NOS-website. Gevolg: oud nieuws. Voorstel: haal de feeds op direct van de bron. Dat voorkomt tevens weer een afhankelijkheid van een Google-dienst. Vergelijk bijvoorbeeld https://feeds.nos.nl/nosnieuwsalgemeen met https://feeds.feedburner.com/nosjournaal. Een volledig overzicht van de feeds vind je op https://nos.nl/feeds.

**Comment by SanderKlootwijk** [comment]
Dag @Fuzzillogic, bedankt voor het melden van deze issue! De NedNieuws app voor Sailfish OS wordt niet meer door mij onderhouden. @a-dekker heeft het onderhoud overgenomen: [https://github.com/a-dekker/harbour-nednieuws](https://github.com/a-dekker/harbour-nednieuws). Het beste kun je hier de issue opnieuw openen.

De nieuwe versie is (nog) niet te downloaden in de Jolla Store, maar wel op openrepos.net: [https://openrepos.net/content/ade/nednieuws](https://openrepos.net/content/ade/nednieuws)

**Comment by a-dekker** [comment]
@Fuzzillogic ik zal de feeds morgen nog even goed langslopen en een nieuwe release op openrepos.net plaatsen, het is nu inderdaad nog wat een mengelmoesje van beide diensten.

**Comment by a-dekker** [comment]
Er zit wel een subtiel verschil in de feeds. Die van de NOS heeft geen end-of-lines in de XML. Dat verklaart ook waarom de opmaak van de tekst soms niet helemaal fijn is. Misschien kan ik dit via een bepaalde 'replace' corrigeren.

**Comment by a-dekker** [comment]
Aangepaste code https://github.com/a-dekker/harbour-nednieuws/commit/17bbc4e959bedcb91f926bf3ec5cc458b171a989 (en een nieuwe release op openrepos.net)
